apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sn3lw8gnq-go
  janus-idp.io/tekton: sn3lw8gnq-go
  backstage.io/kubernetes-id: sn3lw8gnq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sn3lw8gnq-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
