apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sn3lw8gnq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sn3lw8gnq-go 
  name: sn3lw8gnq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sn3lw8gnq-go 
